import type { Dish } from '@/entities/dish'

export const orderItems: Dish[] = [
  {
    id: 1,
    title: 'Напій Pepsi zero',
    slug: 'napij-pepsi-zero',
    weight: null,
    volume: null,
    composition: null,
    price: 72,
    image: '/images/karpatska.jpg',
    type: 'Напій',
    orderCount: 42,
    isNew: false,
    customizable: false,
  },
  {
    id: 4,
    title: 'Вода негазована',
    slug: 'voda-negazovana',
    weight: null,
    volume: 0.5,
    composition: null,
    price: 68,
    image: '/images/pepsi-zero.jpg',
    type: 'Напій',
    orderCount: 44,
    isNew: false,
    customizable: false,
  },
  {
    id: 3,
    title: 'Паста "Карбонара"',
    slug: 'pasta-karbonara',
    weight: 320,
    volume: null,
    composition: 'Вершковий соус з беконом, пармезаном і жовтком',
    price: 329,
    image: '/images/pepsi.png',
    type: 'Паста',
    orderCount: 35,
    isNew: false,
    customizable: true,
  },
]
