import {
  BooleanInput,
  Create,
  ImageInput,
  SimpleForm,
  TextInput
} from 'react-admin'

export const AddDishForm = () => (
  <Create
    resource='dish'
    className='w-full'
  >
    <SimpleForm>
      <TextInput
        source='title'
        label='Назва'
      />
      <TextInput
        source='type'
        label='Тип'
      />
      <TextInput
        source='composition'
        label='Композиція'
      />
      <TextInput
        source='price'
        label='Ціна'
      />
      <TextInput
        source='weight'
        label='Вага'
      />
      <TextInput
        source='volume'
        label='Обсяг'
      />
      <ImageInput
        source='image'
        label='Фото'
      />
      <BooleanInput
        source='customizable'
        label='Кастомізація'
      />
    </SimpleForm>
  </Create>
)
